<a href="https://colab.research.google.com/github/fridymandita/Struktur-Data/blob/main/Struktur_Data_Studi_Kasus_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Dasar Array
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6])

print(arr1d)

[1 2 3 4 5 6]


In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
arr = np.array([1, 1, 1, 1, 1, 1, 1, 1])

print(arr)

[1 1 1 1 1 1 1 1]


In [ ]:
#Tambah Array dan Urut Array
arr = np.array([2, 1, 5, 3, 7, 4, 4, 8])
np.sort(arr)

array([1, 2, 3, 4, 4, 5, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
data = np.array([1, 2, 3])

In [ ]:
data[1]

2

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
print(a[a <= 5])

[1 2 3 4 5]


In [ ]:
#Operasi Array
data = np.array([5, 2])
ones = np.ones(2, dtype=int)
data + ones

array([6, 3])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

In [ ]:
#Max, Min, Sum
data.max()

5

In [ ]:
data.min()

2

In [ ]:
data.sum()

7

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
a.sum()

4.8595784

In [ ]:
#Matriks Array
data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15],[16, 17, 18, 19, 20]])

In [ ]:
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
data[0,1:4]

array([2, 3, 4])

In [ ]:
data[0, 4]

5

In [ ]:
data[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
#Transpose Matriks 
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])